### PR TITLE
update README testing info, update API for server

### PR DESCRIPTION
**Pull request by ericcf**
@eschlange @michaelwehrley @cbrenner04 My instructions are pretty incomplete, so I'd like your help in writing better ones, especially for configuring Xcode and the iOS simulator. Thanks!

### CODE REVIEW

**Comment by eschlange** [comment]
@ericcf Would you like us to add our instructions to this branch, or is there another story for this task?

**Comment by ericcf** [comment]
@eschlange I wrote up the basics in the guides, so maybe I can just link from the medlink readme: https://github.com/cbitstech/guides/tree/master/development/ios

**Comment by michaelwehrley** [comment]
I will see if I can try to configure Xcode and IOS simulator on the ed navigator and give you feedback from that process.

**Comment by eschlange** [comment]
@michaelwehrley Any updates on your configuration test for ED Nav?

**Comment by michaelwehrley** [comment]
I have some small updates to the https://github.com/cbitstech/guides/tree/master/development/ios as I run through it, but as of now I think what I am working on isn't applicable to this.

**Comment by michaelwehrley** [comment]
And my os is 10.7.5 so the instructions may be different since the guides are for 10.10.

**Comment by michaelwehrley** [comment]
@eschlange should I merge this?

**Comment by ericcf** [comment]
Yes please. I'll update documentation once everyone has had a chance to try and follow it. Thanks.

**Comment by eschlange** [comment]
@michaelwehrley Looks good to me.

**Pull request merged**
